// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw2sEDpO-siz80rsNdF5On7e75nnKPs7M',
    appId: '1:998306966825:web:ecb5671adcf77d30d99b38',
    messagingSenderId: '998306966825',
    projectId: 'netflix-c97f0',
    authDomain: 'netflix-c97f0.firebaseapp.com',
    storageBucket: 'netflix-c97f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz4CASF6N23GHEe-fq50Dm2cr8iFYKdQw',
    appId: '1:998306966825:android:cd875c7bcbde9440d99b38',
    messagingSenderId: '998306966825',
    projectId: 'netflix-c97f0',
    storageBucket: 'netflix-c97f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLatWMvJ-EZWU18Kc9FAd-mijBFX-gvYM',
    appId: '1:998306966825:ios:6ea1685f5bd4c550d99b38',
    messagingSenderId: '998306966825',
    projectId: 'netflix-c97f0',
    storageBucket: 'netflix-c97f0.firebasestorage.app',
    iosBundleId: 'com.example.netflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLatWMvJ-EZWU18Kc9FAd-mijBFX-gvYM',
    appId: '1:998306966825:ios:6ea1685f5bd4c550d99b38',
    messagingSenderId: '998306966825',
    projectId: 'netflix-c97f0',
    storageBucket: 'netflix-c97f0.firebasestorage.app',
    iosBundleId: 'com.example.netflix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw2sEDpO-siz80rsNdF5On7e75nnKPs7M',
    appId: '1:998306966825:web:59ef73d7850cea7ed99b38',
    messagingSenderId: '998306966825',
    projectId: 'netflix-c97f0',
    authDomain: 'netflix-c97f0.firebaseapp.com',
    storageBucket: 'netflix-c97f0.firebasestorage.app',
  );
}
